@address = http://localhost:3000/api
@line = [[255, 255, 255], [255, 255, 255], [255, 255, 255], [255, 255, 255], [255, 255, 255], [255, 255, 255], [255, 255, 255], [255, 255, 255], [255, 255, 255], [255, 255, 255], [255, 255, 255], [255, 255, 255], [255, 255, 255], [255, 255, 255], [255, 255, 255], [255, 255, 255]]

POST {{address}}/set-matrix HTTP/1.0
Content-Type: application/json

{
  "matrix": [
    {{line}},
    {{line}},
    {{line}},
    {{line}},
    {{line}},
    {{line}},
    {{line}},
    {{line}},
    {{line}},
    {{line}},
    {{line}},
    {{line}},
    {{line}},
    {{line}},
    {{line}},
    {{line}}
  ]
}
